### PR TITLE
Implement a command line tool

### PR DESCRIPTION
**Pull request by udzura**
Hi! I've added a new command line tool.

I think this is kind and useful for both mruby beginners and freaks!

Please check it out.

### CODE REVIEW

**Comment by matsumotory** [comment]
Thanks! Sorry for my late response.

**Comment by udzura** [comment]
Thanks!!!

**Comment by udzura** [comment]
Also, I created a custom tap!

https://github.com/mrbgems/homebrew-mrbgem-template

```
$ brew tap mrbgems/mrbgem-template
$ brew install mrbgem-template
```

----

If you would like it, please create a release in original `matsumotory/mruby-mrbgem-template` repository...!!

**Comment by matsumotory** [comment]
Thank you for your proposal. It's very useful. So, What should I do in original repository?

**Comment by udzura** [comment]
If you create a git version tag on `matsumotory/mruby-mrbgem-template`, then a release and source download tag will be created! Homebrew uses this!

Like this: https://github.com/udzura/mruby-mrbgem-template/releases
(Temporary I create a release at my fork)

**Comment by matsumotory** [comment]
Thanks! I will create a tag later.

**Comment by matsumotory** [comment]
@udzura I have released v0.1.0 and added you to collaborator. Thank you for your contribute!

**Comment by udzura** [comment]
I found a new release!! Thanks!!
I'll contribute this more <3

**Pull request merged**
