### PR TITLE
mruby has no String#tr

### PR DESCRIPTION
**Pull request by kjunichi**
I got following error.

``` txt
./bin/mruby create.rb 
trace:
    [0] /Users/kjw_junichi/work/mruby/mruby-julia/mruby/build/mrbgems/mruby-mrbgem-template/mrblib/mrb_mrbgem_template.rb:420:in MrbgemTemplate.gemname_to_funcname
    [1] /Users/kjw_junichi/work/mruby/mruby-julia/mruby/build/mrbgems/mruby-mrbgem-template/mrblib/mrb_mrbgem_template.rb:391:in MrbgemTemplate.src_c_data_init
    [2] /Users/kjw_junichi/work/mruby/mruby-julia/mruby/build/mrbgems/mruby-mrbgem-template/mrblib/mrb_mrbgem_template.rb:35:in MrbgemTemplate.initialize
    [3] create.rb:10
/Users/kjw_junichi/work/mruby/mruby-julia/mruby/build/mrbgems/mruby-mrbgem-template/mrblib/mrb_mrbgem_template.rb:420: undefined method 'tr' for "mruby-julia" (NoMethodError)
```

I think mruby has no String#tr method.

### CODE REVIEW

**Comment by matsumotory** [comment]
@udzura What did you have the intention for using tr?

**Comment by udzura** [comment]
Hey, ~~How about declaring mgem deps `core: 'mruby-string-ext'` explicitly in `mrbgem.rake` ?~~ -> see below
@kjunichi

**Comment by udzura** [comment]
I didn't know `String#tr` does not exist in mruby core but `String#gsub` does.
So, this looks nice to be marged.

**Comment by matsumotory** [comment]
Thanks to @kjunichi and @udzura !

**Pull request merged**
